const API_KEY = process.env.REACT_APP_API_KEY;
const CHANNEL_ID = process.env.REACT_APP_API_CHANNEL_ID;

const BASE_URL = `${process.env.REACT_APP_BASE_URL}`;
const BASE_URL_CHANNEL = `${process.env.REACT_APP_BASE_URL}/${CHANNEL_ID}`;

const GET_GRAPH_RECENT_DATA_API = `${BASE_URL_CHANNEL}/feeds.json?api_key=${API_KEY}`;
const GET_GRAPH_SELECTED_DATE_DATA_API = `${BASE_URL_CHANNEL}/feeds.json?api_key=${API_KEY}`;
const GET_GRAPH_CSV_EXPORT_API = `${BASE_URL_CHANNEL}/feeds.csv?start=2011-11-11%2010:10:10&end=2011-11-11%2011:11:11`;

export {
  API_KEY,
  CHANNEL_ID,
  BASE_URL,
  BASE_URL_CHANNEL,
  GET_GRAPH_RECENT_DATA_API,
  GET_GRAPH_SELECTED_DATE_DATA_API,
  GET_GRAPH_CSV_EXPORT_API,
};
